application: chris-gallery
version: 5
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /static/(.*)
  static_dir: static/\1
  upload: static/(.*)

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: main.py
