application: chris-gallery
version: 5
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: robots.txt

- url: /static
  static_dir: static

- url: /.*
  script: main.py
